### ISSUE TITLE
用户自定义 CSS 和 JavaScript

### ISSUE THREAD

**Issue by mogeko** [Mogeko/mogege#19]
允许用户不需要修改 Theme 文件也可以自定义 CSS 和 JavaScript

用户将 CSS 和 JavaScript 分别放入 `/static/css` 和 `/static/js` 中

```
static
├── css
│   └── _custom.css
└── js
    └── _custom.js
```

然后修改 `config.toml` 文件:

```toml
[params.custom]
    css = ["css/_custom.css"]
    js = ["js/_custom.js"]
```
